### ISSUE TITLE
Couldn't create CSV file

### ISSUE THREAD

**Issue by PabloGmz96** [ghuh/bookmark_manager#1]
Hey Kevin, I'm trying to use this Bookmark manager for the first time, I wrote the BOOKMARK_MANAGER_CSV variable into my bashrc file the resource it but the following error still appearing...
```sh
Error: Couldn't create CSV file

Caused by:
    No such file or directory (os error 2)  
```
What I'm doing wrong? Thank you for your support

**Comment by ghuh** [comment]
I suspect that `BOOKMARK_MANAGER_CSV` is either not a valid path or the directory you're trying to create the file in doesn't exist.  The program will only create the CSV file, it won't create any desired parent directories.  You should create those manually.
